pre commit fixed

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,21 +1,15 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
-
-# Define the unwanted lock files
-unwanted_files=("package-lock.json" "yarn.lock" "bun.lockb")
-
 # Check for unwanted lock files in the staged changes
-for file in "${unwanted_files[@]}"; do
-    if git diff --cached --name-only | grep -qE "^$file$"; then
-        echo "Error: Commits containing '$file' are not allowed. Please use Yarn and remove this file from your commit."
-        exit 1
-    fi
+for file in package-lock.json yarn.lock bun.lockb; do
+  if git diff --cached --name-only | grep -qE "^$file$"; then
+    echo "Error: Commits containing '$file' are not allowed. Please use pnpm and remove this file from your commit."
+    exit 1
+  fi
 done
 
-# Allow only yarn.lock, not mandatory but should be the only lock file if present
+# Ensure only pnpm-lock.yaml is present
 if git diff --cached --name-only | grep -qE "^(package-lock\.json|yarn\.lock|bun\.lockb)$"; then
-    echo "Error: Only 'pnpm-lock.yaml' is allowed as a lock file. Please remove any other lock files from your commit."
-    exit 1
+  echo "Error: Only 'pnpm-lock.yaml' is allowed as a lock file. Please use pnpm and remove any other lock files from your commit."
+  exit 1
 fi
 
-npx lint-staged
+npx lint-staged 
